# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:  
          java-version: '17'
          distribution: 'corretto'
          cache: maven

    - name: Maven install
      run: mvn -q install -Dmaven.repo.local=./target/repo -DcreateChecksum=true

    - name: Upload to S3
    - uses: shallwefootball/s3-upload-action@master
      with:
        aws_key_id: ${{ secrets.AWS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
        aws_bucket: 'drwolf-maven-public'
        source_dir: 'target/repo/com/github/drwolf-oss/quarkus-utils'
        destination_dir: 'com/github/drwolf-oss/quarkus-utils'